name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run lint
      run: |
        make lint 

    - name: Run tests
      env: 
        DATABRICKS_KEY: ${{ secrets.DATABRICKS_KEY }}
        SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
        HTTP_PATH: ${{ secrets.HTTP_PATH}}
      run: |
        make test
    
    - name: Run format
      run: |
        make format
